# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: P:/24spring/engs128/workspace/Nestor_Jason/FinalProject-128/Zybo-Z7-10-DMA-hw.xpr/hw/hw.srcs/sources_1/bd/system/ip/system_fir_compiler_1_0/system_fir_compiler_1_0.xci
# IP: The module: 'system_fir_compiler_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: p:/24spring/engs128/workspace/Nestor_Jason/FinalProject-128/Zybo-Z7-10-DMA-hw.xpr/hw/hw.gen/sources_1/bd/system/ip/system_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_fir_compiler_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: p:/24spring/engs128/workspace/Nestor_Jason/FinalProject-128/Zybo-Z7-10-DMA-hw.xpr/hw/hw.gen/sources_1/bd/system/ip/system_fir_compiler_1_0/system_fir_compiler_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_fir_compiler_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: P:/24spring/engs128/workspace/Nestor_Jason/FinalProject-128/Zybo-Z7-10-DMA-hw.xpr/hw/hw.srcs/sources_1/bd/system/ip/system_fir_compiler_1_0/system_fir_compiler_1_0.xci
# IP: The module: 'system_fir_compiler_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: p:/24spring/engs128/workspace/Nestor_Jason/FinalProject-128/Zybo-Z7-10-DMA-hw.xpr/hw/hw.gen/sources_1/bd/system/ip/system_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_fir_compiler_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: p:/24spring/engs128/workspace/Nestor_Jason/FinalProject-128/Zybo-Z7-10-DMA-hw.xpr/hw/hw.gen/sources_1/bd/system/ip/system_fir_compiler_1_0/system_fir_compiler_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_fir_compiler_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
